language: php
sudo: required

matrix:
  include:
    - php: 5.6
      env:
        - qaExtended=true
    - php: 7.0
      env:
        - qaExtended=true
    - php: 7.1
    - php: 7.2
      env:
        - dropPlatform=false
    - php: nightly
      env:
        - dropPlatform=false
    - php: 5.6
      env:
        - dependencies=lowest
    - php: 7.0
      env:
        - dependencies=lowest
    - php: 7.1
      env:
        - dependencies=lowest
    - php: 7.2
      env:
        - dependencies=lowest
        - dropPlatform=false
    - php: nightly
      env:
        - dependencies=lowest
        - dropPlatform=false
    - php: 5.6
      env:
        - dependencies=highest
    - php: 7.0
      env:
        - dependencies=highest
    - php: 7.1
      env:
        - dependencies=highest
    - php: 7.2
      env:
        - dependencies=highest
        - dropPlatform=false
    - php: nightly
      env:
        - dependencies=highest
        - dropPlatform=false

install:
  - composer install

script:
  - vendor/bin/phpunit
